#include "telemetry_publisher/publisher.h"

#include "telemetry.pb.h"  // generated by protoc

#include <spdlog/spdlog.h>

namespace tp {

Publisher::Publisher(Config config)
    : config_(std::move(config)) {
    socket_     = std::make_unique<UdpSocket>(
        config_.publisher.target_host, config_.publisher.target_port);
    trajectory_ = std::make_unique<Trajectory>(config_.trajectory);
    generator_  = std::make_unique<TelemetryGenerator>(
        config_.publisher.drone_id, config_.simulation);
}

Publisher::~Publisher() {
    stop();
    wait();
}

void Publisher::start() {
    running_ = true;
    generator_thread_ = std::thread([this] { generator_loop(); });
    publisher_thread_ = std::thread([this] { publisher_loop(); });
    spdlog::info("Publisher started ({} Hz)", config_.publisher.publish_rate_hz);
}

void Publisher::stop() {
    bool was_running = running_.exchange(false);
    if (was_running) {
        spdlog::info("Stopping publisher...");
        queue_cv_.notify_all();  // Wake publisher_thread if it is blocking
    }
}

void Publisher::wait() {
    if (generator_thread_.joinable()) {
        generator_thread_.join();
        spdlog::debug("Generator thread joined");
    }
    if (publisher_thread_.joinable()) {
        publisher_thread_.join();
        spdlog::debug("Publisher thread joined");
    }
    spdlog::info("Joined threads");
}

// ── Generator loop (producer) ─────────────────────────────────────────────────

void Publisher::generator_loop() {
    using namespace std::chrono;

    const int    rate_hz    = config_.publisher.publish_rate_hz;
    const auto   interval   = milliseconds(1000 / rate_hz);
    milliseconds elapsed_ms{0};

    spdlog::debug("Generator loop: {} Hz, interval={}ms", rate_hz, interval.count());

    while (running_) {
        auto tick_start = steady_clock::now();

        auto pos_opt = trajectory_->advance(interval);
        if (!pos_opt) {
            spdlog::info("Trajectory finished (loop=false); stopping");
            stop();
            break;
        }

        auto pkt = generator_->generate(*pos_opt, elapsed_ms);
        elapsed_ms += interval;

        {
            std::unique_lock<std::mutex> lock(queue_mutex_);
            if (queue_.size() < kMaxQueueSize) {
                queue_.push(std::move(pkt));
            } else {
                spdlog::warn("Queue full — dropping packet (seq={})", pkt.sequence());
            }
        }
        queue_cv_.notify_one();

        // Precise sleep: account for time spent generating
        auto elapsed = steady_clock::now() - tick_start;
        if (elapsed < interval) {
            std::this_thread::sleep_for(interval - elapsed);
        }
    }
}

// ── Publisher loop (consumer) ─────────────────────────────────────────────────

void Publisher::publisher_loop() {
    spdlog::debug("Publisher loop started");

    while (running_ || [&] {
        std::lock_guard<std::mutex> lock(queue_mutex_);
        return !queue_.empty();
    }()) {
        drone_platform::telemetry::TelemetryPacket pkt;

        {
            std::unique_lock<std::mutex> lock(queue_mutex_);
            queue_cv_.wait(lock, [this] {
                return !queue_.empty() || !running_;
            });
            if (queue_.empty()) break;
            pkt = std::move(queue_.front());
            queue_.pop();
        }

        // Serialise + send
        std::string serialised;
        if (!pkt.SerializeToString(&serialised)) {
            spdlog::error("Failed to serialise TelemetryPacket seq={}", pkt.sequence());
            continue;
        }

        std::vector<uint8_t> bytes(serialised.begin(), serialised.end());
        ssize_t sent = socket_->send(bytes);

        if (sent > 0) {
            spdlog::debug("Sent {} bytes (seq={} drone={})",
                          sent, pkt.sequence(), pkt.drone_id());
        }
    }

    spdlog::debug("Publisher loop exited");
}

}  // namespace tp
