#include "telemetry_publisher/telemetry_generator.h"

#include "telemetry.pb.h"  // generated by protoc

#include <algorithm>
#include <chrono>

namespace tp {

TelemetryGenerator::TelemetryGenerator(std::string drone_id, SimulationConfig sim_config)
    : drone_id_(std::move(drone_id)),
      sim_config_(sim_config),
      rng_(std::random_device{}()) {}

drone_platform::telemetry::TelemetryPacket
TelemetryGenerator::generate(const Position& pos, std::chrono::milliseconds elapsed) {
    using namespace std::chrono;

    drone_platform::telemetry::TelemetryPacket pkt;

    pkt.set_drone_id(drone_id_);
    pkt.set_sequence(sequence_++);

    // Wall-clock timestamp
    auto now_ms = duration_cast<milliseconds>(
                      system_clock::now().time_since_epoch())
                      .count();
    pkt.set_timestamp_ms(now_ms);

    // Position
    pkt.set_latitude(pos.lat);
    pkt.set_longitude(pos.lon);
    pkt.set_altitude_m(pos.alt);

    // Motion
    pkt.set_speed_mps(pos.speed_mps);
    pkt.set_heading_deg(pos.heading_deg);

    // Battery: drain linearly from 100 %
    double elapsed_sec  = elapsed.count() / 1000.0;
    double battery      = 100.0 - sim_config_.battery_drain_per_second * elapsed_sec;
    pkt.set_battery_percent(std::max(0.0, battery));

    // Signal: base + Gaussian noise
    std::normal_distribution<double> noise(0.0, sim_config_.signal_noise);
    double signal = std::clamp(sim_config_.signal_base + noise(rng_), 0.0, 100.0);
    pkt.set_signal_strength(signal);

    return pkt;
}

}  // namespace tp
